var dropdown_options = [
    { value: "numIncarcerated",
      text: "Number Incarcerated" },
    { value: "numIncarceratedMale",
      text: "Number Males Incarcerated" },
    { value: "numIncarceratedFemale",
      text: "Number Females Incarcerated" },
    { value: "numCrimeCommitted",
      text: "Number of Crimes Committed" },
    { value: "numCrimeCommittedMale",
      text: "Number of Crimes Committed by Males" },
    { value: "numCrimeCommittedFemale",
      text: "Number of Crimes Committed by Females" },
    { value: "population",
      text: "County Population" },
    { value: "populationMale",
      text: "County Male Population" },
    { value: "populationFemale",
      text: "County Female Population" },
    { value: "incarcerationRate",
      text: "Incarceration Rate" },
    { value: "incarcerationRateMale",
      text: "Incarceration Rate Male" },
    { value: "incarcerationRateFemale",
      text: "Incarceration Rate Female" },
    { value: "countyHispanic",
      text: "County Hispanic Population" },
    { value: "countyHispanicPct",
      text: "County Hispanic Percent" },
    { value: "countyNHWhite",
      text: "County NH-White Population" },
    { value: "countyNYWhitePct",
      text: "County NH-White Percent" },
    { value: "countyNHBlackPct",
      text: "County NH-Black Percent" },
    { value: "countyNHOther",
      text: "County NH-Other Population" },
    { value: "countyNHOtherPct",
      text: "County NH-Other Percent" },
    { value: "prisonHispanic",
      text: "Prison Hispanic Population" },
    { value: "prisonHispanicPct",
      text: "Prison Hispanic Percent" },
    { value: "prisonNHWhite",
      text: "Prison NHWhite Population" },
    { value: "prisonNHWhitePct",
      text: "Prison NHWhite Percent" },
    { value: "prisonNHBlack",
      text: "Prison NHBlack Population" },
    { value: "prisonNHBlackPct",
      text: "Prison NHBlack Percent" },
    { value: "prisonNHOther",
      text: "Prison NH Other Race/Ethn Population" },
    { value: "prisonNHOtherPct",
      text: "Prison NH Other Race/Ethn Percent" },
    { value: "incarcerationRateHispanic",
      text: "Incarceration Rate Hispanic" },
    { value: "incarcerationRateNHWhite",
      text: "Incarceration Rate NHWhite" },
    { value: "incarcerationRateNHBlack",
      text: "Incarceration Rate NHBlack" },
    { value: "incarcerationRateNHOther",
      text: "Incarceration Rate NH Other" },
    ]
