var dropdown_options = [
{ value: "numIncarcerated",  text: "Number Incarcerated" },
{ value: "numIncarceratedMale",  text: "Number Males Incarcerated" },
{ value: "numIncarceratedFemale",text: "Number Females Incarcerated" },
{ value: "numCrimeCommitted",text: "Number of Crimes Committed in County" },
{ value: "numCrimeCommittedMale",text: "Number of Crimes Committed in County by Males" },
{ value: "numCrimeCommittedFemale",text: "Number of Crimes Committed in County by Females" },
{ value: "population",  text: "County Population" },
{ value: "malepopulation",  text: "County Population Male" },
{ value: "femalepopulation",  text: "County Population Female" },
{ value: "incarcerationRate",text: "Incarceration Rate" },
{ value: "maleincarcerationRate",  text: "Male Incarceration Rate" },
{ value: "femaleincarcerationRate",  text: "Female Incarceration Rate" },
{ value: "incarceratedOverCommitted",  text: "Number Incarcerated in County/Number Crimes Committed in County" },
]
